### ISSUE TITLE
copy message Id doesn't work

### ISSUE THREAD

**Issue by dragonxtek** [code-orange/Gmail-message-ID-finder#1]
Can you check if it still works?
I click on Copy message ID, appears a loading popup but nothing happens, my clipboard still empty

**Comment by timvdalen** [comment]
It works for me!
The message I got from GitHub has id `rfc822msgid:code-orange/Gmail-message-ID-finder/issues/1@github.com`.
What version of Gmail are you on? Personal or business?
Can you open your devconsole and note any errors that pop up when you click the button?

**Comment by dragonxtek** [comment]
In personal version it works, but with the following warning:
![Selection_985](https://user-images.githubusercontent.com/10552658/82278668-c3d66180-9958-11ea-9d61-13221517ca2f.png)
In business version it doesn't work (I guess it's because by CORS policy). Devconsole returns the following:
![Selection_986](https://user-images.githubusercontent.com/10552658/82278723-dea8d600-9958-11ea-9f0f-d7ce32801468.png)

**Comment by timvdalen** [comment]
That's interesting! What domain are you on for business? We're on `https://mail.google.com/`, our own domain has been redirecting to that for years.

**Comment by dragonxtek** [comment]
I have the same domain...
I created a gif to show the process:

![gmail](https://user-images.githubusercontent.com/10552658/82506614-47658f00-9ace-11ea-8d26-4cf2d6b439c0.gif)

**Comment by dragonxtek** [comment]
did you find out what could be wrong? it only works for my personal gmail account, but not for the business one

**Comment by dragonxtek** [comment]
I fixed it! 
For personal version works with:
```fetch('https://mail.google.com/mail/u/0/?ui=2&ik=' + GLOBALS[9] + '&view=om&th=' + event.data.id, {credentials: 'include'})```
For business version works with:
```fetch('https://mail.google.com/mail/u/1/?ui=2&ik=' + GLOBALS[9] + '&view=om&th=' + event.data.id, {credentials: 'include'})```
Can you add it to your code?
Thanks!

**Comment by timvdalen** [comment]
Hi @dragonxtek thanks for looking into this :).
The `/0/` or `/1/` part references the profile you're using, so I guess you are logged into multiple Google profiles within the same Chrome profile?
I think I should be able to detect this, so I think I can fix this!

I'll try to ship a new version this week.
Thanks again for debugging this.

**Comment by dragonxtek** [comment]
I'm actually  logged into multiple Google profiles within the same Chrome profile, in fact it's about 5.
Thank you for your quick response

**Comment by timvdalen** [comment]
I've created a new version and submitted it to the Chrome Web Store! Hopefully it gets approved soon.

Thanks again for debugging this with me!
